packages:
  - "apps/*"
allowBuilds:
  '@apollo/protobufjs': true
  '@google/genai': true
  '@nestjs/core': set this to true or false
  bcrypt: true
  better-sqlite3: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
