import { CatalogProduct } from '@/components/home/CategoryProductGrid';

export const CATALOG_PRODUCTS: CatalogProduct[] = [
  // PHONES
  {
    id: '1',
    slug: 'iphone-15-pro-max-256gb-natural-titanium',
    name: 'iPhone 15 Pro Max 256GB (Natural Titanium)',
    category: 'Phones',
    condition: 'Pristine',
    batteryHealth: 99,
    priceNgn: 1250000,
    retailNgn: 1600000,
    preview: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
    description: 'Canada-sourced iPhone 15 Pro Max in Natural Titanium. Grade A+ Pristine condition with 99% Battery Health. Powered by the A17 Pro chip, aerospace-grade titanium frame, and 5x optical zoom camera. Factory unlocked with verified clean IMEI.',
    imeiStatus: 'Clean & Verified',
  },
  {
    id: '2',
    slug: 'iphone-14-pro-128gb-space-black',
    name: 'iPhone 14 Pro 128GB (Space Black)',
    category: 'Phones',
    condition: 'Pristine',
    batteryHealth: 95,
    priceNgn: 840000,
    retailNgn: 1100000,
    preview: 'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?auto=format&fit=crop&w=800&q=80',
    description: 'Canada-sourced iPhone 14 Pro in Space Black. Features Dynamic Island, 48MP Pro camera system, and Always-On display. 95% Battery Health, 100% genuine Apple components with 7-day guarantee.',
    imeiStatus: 'Clean & Verified',
  },
  {
    id: '3',
    slug: 'iphone-13-128gb-midnight-blue',
    name: 'iPhone 13 128GB (Midnight Blue)',
    category: 'Phones',
    condition: 'Excellent',
    batteryHealth: 92,
    priceNgn: 520000,
    retailNgn: 680000,
    preview: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
    description: 'Direct Canada import iPhone 13. Super Retina XDR OLED display, A15 Bionic, Cinematic mode. Tested and verified 92% battery health, completely clean global IMEI, unlocked for all Nigerian networks.',
    imeiStatus: 'Clean & Verified',
  },
  {
    id: '4',
    slug: 'samsung-galaxy-s23-ultra-256gb-phantom-black',
    name: 'Samsung Galaxy S23 Ultra 5G 256GB (Phantom Black)',
    category: 'Phones',
    condition: 'Pristine',
    batteryHealth: 96,
    priceNgn: 820000,
    retailNgn: 1150000,
    preview: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
    description: 'Canada-sourced Galaxy S23 Ultra. Built-in S Pen, 200MP camera sensor, 100x Space Zoom, Snapdragon 8 Gen 2 for Galaxy. Battery health tested at 96%. Pristine grade with zero scratches.',
    imeiStatus: 'Clean & Verified',
  },
  {
    id: '5',
    slug: 'google-pixel-8-pro-128gb-obsidian',
    name: 'Google Pixel 8 Pro 128GB (Obsidian)',
    category: 'Phones',
    condition: 'Pristine',
    batteryHealth: 98,
    priceNgn: 690000,
    retailNgn: 920000,
    preview: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    description: 'Directly imported from Canada. Google Tensor G3, legendary computational photography, Best Take, Magic Audio Eraser, 120Hz Super Actua display. 98% battery health and unlocked for all carriers.',
    imeiStatus: 'Clean & Verified',
  },

  // LAPTOPS
  {
    id: '6',
    slug: 'macbook-pro-14-m2-pro-16gb-512gb-space-gray',
    name: 'MacBook Pro 14" (M2 Pro, 16GB RAM, 512GB SSD, Space Gray)',
    category: 'Laptops',
    condition: 'Pristine',
    batteryHealth: 97,
    priceNgn: 1750000,
    retailNgn: 2400000,
    preview: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    description: 'Canada corporate off-lease unit in mint condition. Apple M2 Pro (10-core CPU, 16-core GPU), 16GB unified memory, 512GB SSD, Liquid Retina XDR 120Hz ProMotion display. Battery cycle count: only 34 cycles (97% health). Includes MagSafe 3 charger.',
    imeiStatus: 'Clean Serial',
  },
  {
    id: '7',
    slug: 'macbook-air-13-m2-8gb-256gb-midnight',
    name: 'MacBook Air 13" (M2, 8GB RAM, 256GB SSD, Midnight)',
    category: 'Laptops',
    condition: 'Pristine',
    batteryHealth: 98,
    priceNgn: 980000,
    retailNgn: 1350000,
    preview: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    description: 'Direct Canada import MacBook Air M2 in sought-after Midnight color. Redesigned flat chassis, 13.6-inch Liquid Retina display, MagSafe charging, 1080p FaceTime HD camera. Ultra-low battery cycles (18 cycles, 98% health).',
    imeiStatus: 'Clean Serial',
  },
  {
    id: '8',
    slug: 'macbook-air-13-m1-8gb-256gb-silver',
    name: 'MacBook Air 13" (M1, 8GB RAM, 256GB SSD, Silver)',
    category: 'Laptops',
    condition: 'Excellent',
    batteryHealth: 93,
    priceNgn: 640000,
    retailNgn: 880000,
    preview: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80',
    description: 'The best value developer & student laptop in Nigeria. Apple M1 silicon, silent fanless thermal design, all-day battery life (93% health, 48 cycles). Fully tested keyboard, trackpad, and Retina display.',
    imeiStatus: 'Clean Serial',
  },
  {
    id: '9',
    slug: 'dell-xps-15-9520-i7-16gb-512gb-oled',
    name: 'Dell XPS 15 9520 (i7-12700H, 16GB RAM, 512GB SSD, 3.5K OLED)',
    category: 'Laptops',
    condition: 'Pristine',
    batteryHealth: 92,
    priceNgn: 1150000,
    retailNgn: 1650000,
    preview: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80',
    description: 'High-performance creative workstation imported from Canada. Intel Core i7-12700H, NVIDIA RTX 3050 graphics, 16GB DDR5, 3.5K OLED InfinityEdge touch screen. CNC machined aluminum & carbon fiber palm rest.',
    imeiStatus: 'Clean Service Tag',
  },

  // HEADPHONES
  {
    id: '10',
    slug: 'airpods-max-space-gray',
    name: 'AirPods Max (Space Gray with Smart Case)',
    category: 'Headphones',
    condition: 'Pristine',
    batteryHealth: 96,
    priceNgn: 480000,
    retailNgn: 650000,
    preview: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    description: 'Pristine Canada-tested AirPods Max. Custom acoustic design, high-fidelity audio, active noise cancellation with Transparency mode, personalized spatial audio with dynamic head tracking. Earpads sanitized and pristine.',
    imeiStatus: 'Verified Serial',
  },
  {
    id: '11',
    slug: 'airpods-pro-2nd-gen-usbc',
    name: 'AirPods Pro 2nd Gen (USB-C MagSafe Case)',
    category: 'Headphones',
    condition: 'Pristine',
    batteryHealth: 100,
    priceNgn: 220000,
    retailNgn: 310000,
    preview: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=80',
    description: 'Up to 2x more Active Noise Cancellation, Adaptive Audio, and USB-C MagSafe Charging Case with built-in speaker and lanyard loop. Battery 100% capacity with verified serial number.',
    imeiStatus: 'Verified Serial',
  },
  {
    id: '12',
    slug: 'sony-wh1000xm5-wireless-black',
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling (Black)',
    category: 'Headphones',
    condition: 'Pristine',
    batteryHealth: 98,
    priceNgn: 340000,
    retailNgn: 460000,
    preview: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    description: 'Industry-leading noise cancellation powered by dual processors and 8 microphones. Auto NC Optimizer, exceptional call quality, 30-hour battery life. Canada verified unit with original travel case.',
    imeiStatus: 'Verified Serial',
  },

  // SMARTWATCHES
  {
    id: '13',
    slug: 'apple-watch-ultra-2-49mm-titanium',
    name: 'Apple Watch Ultra 2 (Titanium, 49mm, Orange Alpine Loop)',
    category: 'Smartwatches',
    condition: 'Pristine',
    batteryHealth: 100,
    priceNgn: 750000,
    retailNgn: 1050000,
    preview: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
    description: 'Rugged 49mm aerospace-grade titanium case, precision dual-frequency GPS, up to 36 hours of battery life (100% battery health). Cellular + GPS unlocked for Nigeria. Bright 3000 nits display.',
    imeiStatus: 'Clean EID/IMEI',
  },
  {
    id: '14',
    slug: 'apple-watch-series-9-45mm-midnight',
    name: 'Apple Watch Series 9 GPS 45mm (Midnight Aluminum)',
    category: 'Smartwatches',
    condition: 'Pristine',
    batteryHealth: 99,
    priceNgn: 380000,
    retailNgn: 520000,
    preview: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
    description: 'S9 SiP chip with Double Tap gesture, brighter display, on-device Siri, and Precision Finding for iPhone. Battery health 99%, completely clean screen and casing.',
    imeiStatus: 'Verified Serial',
  },
  {
    id: '15',
    slug: 'samsung-galaxy-watch-6-classic-47mm-black',
    name: 'Samsung Galaxy Watch 6 Classic (47mm, Bluetooth, Black)',
    category: 'Smartwatches',
    condition: 'Pristine',
    batteryHealth: 97,
    priceNgn: 260000,
    retailNgn: 360000,
    preview: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    description: 'Iconic rotating bezel, sapphire crystal glass, advanced sleep coaching, BIA body composition analysis. Tested 97% battery health with original magnetic link strap.',
    imeiStatus: 'Verified Serial',
  },

  // CAMERAS
  {
    id: '16',
    slug: 'sony-alpha-a7-iii-full-frame-lens-kit',
    name: 'Sony Alpha A7 III Full-Frame (Body + 28-70mm OSS Lens)',
    category: 'Cameras',
    condition: 'Pristine',
    batteryHealth: 95,
    priceNgn: 1450000,
    retailNgn: 1950000,
    preview: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    description: 'Canada-sourced Sony A7 III with FE 28-70mm f/3.5-5.6 OSS kit lens. 24.2MP Exmor R CMOS full-frame sensor, 4K HDR video, 5-axis optical image stabilization. Shutter count verified under 4,200 actuations. Sensor 100% clean.',
    imeiStatus: 'Clean Serial',
  },
  {
    id: '17',
    slug: 'canon-eos-r6-mirrorless-body',
    name: 'Canon EOS R6 Full-Frame Mirrorless Body (4K60p, 20.1MP)',
    category: 'Cameras',
    condition: 'Pristine',
    batteryHealth: 96,
    priceNgn: 1680000,
    retailNgn: 2250000,
    preview: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=800&q=80',
    description: 'High-speed sports, wedding, and low-light creator camera imported from Canada. 20.1MP full-frame CMOS sensor, up to 20 fps electronic shutter, 4K60p 10-bit internal recording, Dual Pixel CMOS AF II. Shutter count under 6,800. Pristine sensor.',
    imeiStatus: 'Clean Serial',
  },

  // ACCESSORIES
  {
    id: '18',
    slug: 'apple-20w-usbc-power-adapter-braided-cable',
    name: 'Apple 20W USB-C Power Adapter + Braided USB-C Cable',
    category: 'Accessories',
    condition: 'Pristine',
    batteryHealth: 100,
    priceNgn: 32000,
    retailNgn: 45000,
    preview: 'https://images.unsplash.com/photo-1622445262464-84b14e32452e?auto=format&fit=crop&w=800&q=80',
    description: 'Genuine Canada-sourced Apple 20W Power Adapter with official Apple 1m Braided USB-C to USB-C / Lightning Cable. Fast charge iPhone from 0 to 50% in 30 minutes.',
    imeiStatus: 'Original Apple Serial',
  },
  {
    id: '19',
    slug: 'apple-magsafe-battery-pack-portable',
    name: 'Apple MagSafe Battery Pack (Wireless Portable Charger)',
    category: 'Accessories',
    condition: 'Pristine',
    batteryHealth: 97,
    priceNgn: 65000,
    retailNgn: 95000,
    preview: 'https://images.unsplash.com/photo-1609592424367-279c13b28b7b?auto=format&fit=crop&w=800&q=80',
    description: 'Snaps on with perfectly aligned magnets for safe, reliable wireless charging on iPhone 12, 13, 14, and 15 series. Charge on the go without cables. Battery health tested at 97%.',
    imeiStatus: 'Verified Serial',
  },
  {
    id: '20',
    slug: 'anker-735-gan-65w-charger',
    name: 'Anker 735 GaN 65W 3-Port Fast Charger (2x USB-C + 1x USB-A)',
    category: 'Accessories',
    condition: 'Pristine',
    batteryHealth: 100,
    priceNgn: 48000,
    retailNgn: 68000,
    preview: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    description: 'Power up your MacBook, iPhone, and Apple Watch simultaneously from one tiny wall plug. GaNPrime technology with intelligent power allocation and ActiveShield temperature protection.',
    imeiStatus: 'Verified Serial',
  }
];
